# Generated by Django 5.0 on 2024-05-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
