# Generated by Django 5.0 on 2024-05-16 15:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0002_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseName', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course')),
                ('courseFee', models.IntegerField()),
                ('courseDuration', models.IntegerField()),
                ('syllabus', ckeditor.fields.RichTextField(default='syllabus')),
                ('aboutCourse', ckeditor.fields.RichTextField(default='aboutCourse')),
                ('stars', models.IntegerField(default=3)),
            ],
        ),
    ]
