# Generated by Django 5.0 on 2024-06-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0003_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=60)),
                ('trainer_designation', models.CharField(max_length=140)),
                ('trainer_experience', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startupapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('candidateTd', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('alternateNumber', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('collegeName', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('landmark', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=140)),
                ('pincode', models.IntegerField()),
                ('companyName', models.CharField(blank=True, max_length=140, null=True)),
                ('designation', models.CharField(max_length=140)),
                ('qualification', models.CharField(max_length=100)),
                ('computerKnowledge', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=140)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='startupapp.trainer')),
            ],
        ),
    ]
