# Generated by Django 5.0 on 2024-06-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0004_trainer_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fatherName',
            new_name='fathername',
        ),
    ]
