# Generated by Django 5.0 on 2024-06-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0006_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='candidateTd',
            new_name='candidateId',
        ),
    ]
