# Generated by Django 5.0 on 2024-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0008_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='logintime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='logouttime',
            field=models.TimeField(),
        ),
    ]
