# Generated by Django 5.0 on 2024-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
